name: Run EXE on Local Runner

on: [workflow_dispatch]  

jobs:
  run-exe:
    runs-on: windows-latest
    steps:
      - name: Find Google Chrome Path
        shell: pwsh
        run: |
          $chromePath = "C:\Program Files\Google\Chrome\Application\chrome.exe"
          if (Test-Path $chromePath) {
            Write-Output "Google Chrome found at: $chromePath"
          } else {
            Write-Output "Google Chrome not found."
          }
